import Header from "@/components/Header";
import Head from "next/head";
import Footer from "../Footer";

export interface ILayout extends React.ComponentPropsWithoutRef<"div"> {
  title: string;
}

const Layout: React.FC<ILayout> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
