import Header from '@/components/Header/Header';
import usePersistedState from '@/hooks/usePersistedState';
import { GlobalStyles, darkTheme, lightTheme } from '@/styles/global';
import Head from 'next/head';
import { DefaultTheme, ThemeProvider } from 'styled-components';
import { Wrapper } from './Layout.styles';

export interface ILayout extends React.ComponentPropsWithoutRef<'div'> {
  title: string;
}

const Layout: React.FC<ILayout> = ({ children, title }) => {
  const [theme, setTheme] = usePersistedState<DefaultTheme>('theme', darkTheme);

  const toggleTheme = () => {
    setTheme(theme.body === '#b2bec3' ? darkTheme : lightTheme);
  };
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <Header theme={theme} toggleTheme={toggleTheme} />
        <Wrapper>{children}</Wrapper>
      </ThemeProvider>
    </>
  );
};

export default Layout;
